### ISSUE TITLE
Добавить requirements.txt и Readme

### ISSUE THREAD

**Issue by kiriharu** [dvjdjvu/vkMusicDownloader#1]
Внезапно, это один из скриптов, который заработал и позволил мне скачать музыку из ВК не изобретая собственный костыль (за что спасибо автору).

Собственно, хотелось бы что-бы появилось нормальное ридми и requirements.txt, в котором будут зависимости, ибо не думаю что кто-то еще поймет, какие пакеты нужно скачать для работы скрипта.

**Comment by dvjdjvu** [comment]
Ок, постараюсь сделать .

**Comment by dvjdjvu** [comment]
> Внезапно, это один из скриптов, который заработал и позволил мне скачать музыку из ВК не изобретая собственный костыль (за что спасибо автору).
> 
> Собственно, хотелось бы что-бы появилось нормальное ридми и requirements.txt, в котором будут зависимости, ибо не думаю что кто-то еще поймет, какие пакеты нужно скачать для работы скрипта.

Сделал.
