### ISSUE TITLE
Пропуски/глитчи в загруженных аудиозаписях

### ISSUE THREAD

**Issue by angrykirc** [dvjdjvu/vkMusicDownloader#10]
При использовании последней актуальной версии ffmpeg загружаемые с помощью этого скрипта аудиозаписи имеют ощутимые пропуски и глитчи.
См. https://trac.ffmpeg.org/ticket/8490
Исправляется добавлением **-http_persistent false** в аргументы ffmpeg.

**Comment by dvjdjvu** [comment]
Спасибо, добавил.
