### ISSUE TITLE
Не удалось установить BeautifulSoup

### ISSUE THREAD

**Issue by ivnish** [dvjdjvu/vkMusicDownloader#3]
**Ubuntu 20.04**

`pip3 install -r requirements.txt`

Requirement already satisfied: requests>=2.18.4 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (2.22.0)
Collecting vk_api>=11.5.0
  Downloading vk_api-11.8.0.tar.gz (33 kB)
ERROR: Could not find a version that satisfies the requirement BeautifulSoup>=4.8.0 (from -r requirements.txt (line 3)) (from versions: 3.2.0, 3.2.1, 3.2.2)
ERROR: No matching distribution found for BeautifulSoup>=4.8.0 (from -r requirements.txt (line 3))

Решение:

BeautifulSoup>=4.8.0 -> BeautifulSoup**4**>=4.8.0

**Comment by dvjdjvu** [comment]
up
