### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by dan4ik605743** [dvjdjvu/vkMusicDownloader#4]
Бесконечно думает.
![image](https://user-images.githubusercontent.com/86075850/159443733-fa10257b-6ac6-4a20-a213-9362f98b7aab.png)

**Comment by dvjdjvu** [comment]
![image](https://user-images.githubusercontent.com/1677773/159448607-629aaa2a-d6fe-4835-b725-004c5574e2b0.png)
Только что проверил. Сколько весит у Вас, интернет соединение не отвалилось? Что за система?
id своего профиля правильно вбили? и есть ли у вас доступ к тому профилю откуда вы хотите скачать музыку?

Все мое скачалось:
![image](https://user-images.githubusercontent.com/1677773/159451269-81992311-377e-45a7-b14e-4da2c7d21116.png)

**Comment by dan4ik605743** [comment]
Система nixos, интернет не отваливается, весит что? id профиля правильно вбил. Есть ли доступ? Ну я же залогинился под свой же профиль вк и хочу оттуда скачать музыку

**Comment by dan4ik605743** [comment]
У меня в профиле около 2000 аудио, сколько должен думать?

**Comment by dan4ik605743** [comment]
И сейчас заметил что у меня не было ffmpeg, установил создалась папка music но в ней пусто и ожидание, сейчас попробую подождать минут 5

**Comment by dan4ik605743** [comment]
Думаю дело в FHS, сейчас попробую разобраться, если оно работает, значит и я запущу или не в нем дело

**Comment by dan4ik605743** [comment]
![image](https://user-images.githubusercontent.com/86075850/159462226-45a7489b-a0b4-49ac-b884-f112d2457b74.png)
хм оказалось на много проще

**Comment by dan4ik605743** [comment]
ввел рандом, походу дело в моей странице, что может быть не так?

**Comment by dan4ik605743** [comment]
у меня 1700-1800 аудио, может быть из за этого так долго считает или что то с профилем?

**Comment by dvjdjvu** [comment]
Возможно, у меня ~180. Картинку выше удалите, там ваш логин и пароль ;)

**Comment by dan4ik605743** [comment]
![image](https://user-images.githubusercontent.com/86075850/159463184-2a5f2e0f-8bc5-45ae-b125-ad7837a0c696.png)
а вот я скачиваю музыку друга

**Comment by dan4ik605743** [comment]
> Возможно, у меня ~180. Картинку выше удалите, там ваш логин и пароль ;)

ой бля) не разу такого не допускал))

**Comment by dan4ik605743** [comment]
![image](https://user-images.githubusercontent.com/86075850/159463377-565fe05c-e8ac-4c3f-bab2-9dbc4e2808af.png)
ну это ладно, факт что оно работает

**Comment by dan4ik605743** [comment]
может с настройками профиля что не так

**Comment by dan4ik605743** [comment]
но это врятли, я же логинюсь под своей страницой с правами все должно быть нормально, мне все больше и больше кажется что дело в таком размере.

**Comment by dan4ik605743** [comment]
![image](https://user-images.githubusercontent.com/86075850/159464352-e118db66-7d07-4001-9bc6-8b196eab1d48.png)
музыка битая скачивается

**Comment by dan4ik605743** [comment]
кусок один обрывается и так везде и именно 1

**Comment by dvjdjvu** [comment]
Дайте id своей страницы, попробую скачать ваше.

**Comment by dan4ik605743** [comment]
> Дайте id своей страницы, попробую скачать ваше.

253066476

**Comment by dan4ik605743** [comment]
музыку открыл

**Comment by dan4ik605743** [comment]
@dvjdjvu  ну что там?

**Comment by dan4ik605743** [comment]
Уже впринципе не важно, за все спасибо) Нашел скрипт, скачал всю музыку, отличный скрипт кстати, быстрый и все ровно.
https://gist.github.com/Whatisone/0f8acc4cad4f4e5fe95d54e5fc454472

**Comment by dan4ik605743** [comment]
Аудио пока открытые, напишите как проверите, если вам это еще нужно) Потом закрою

**Comment by dvjdjvu** [comment]
Завтра постараюсь посмотреть.

**Comment by dvjdjvu** [comment]
Запрос на получении audio висел минут 5, потом началась загрузка.
![image](https://user-images.githubusercontent.com/1677773/159928481-8fa6b84c-2899-4aa8-aa47-13f6c78e025f.png)
скачал почти 3 гига, дальше не стал, а то на виртуалке место закончится
![image](https://user-images.githubusercontent.com/1677773/159928578-f6dd0952-469b-4e9f-884f-70a1f873ebc3.png)
все что скачал играет
![image](https://user-images.githubusercontent.com/1677773/159928704-5b2f0807-0992-4ca4-9997-20af6795fa95.png)

**Comment by dan4ik605743** [comment]
получается надо было просто подождать, хорошо. Но музыка то битая.

**Comment by dan4ik605743** [comment]
> ![image](https://user-images.githubusercontent.com/86075850/159464352-e118db66-7d07-4001-9bc6-8b196eab1d48.png) музыка битая скачивается

Вот я скачал не много, и послушал, куски обрываются

**Comment by dan4ik605743** [comment]
Проверьте у вас так же, проганите через cvlc любой трек и покажите лог на наличии ошибок, если нет было бы идеально

**Comment by dan4ik605743** [comment]
Скрипт накачал нерабочей музыки, не воспроизводится))

**Comment by dan4ik605743** [comment]
Крч музыка обрывается кусками, слушать не возможно, проверь у тебя как, наверняка это везде, пофиксишь будет идеальный скрипт
