### ISSUE TITLE
На Windows10 не работает параллельная загрузка песен

### ISSUE THREAD

**Issue by my-dev-92** [dvjdjvu/vkMusicDownloader#7]
Такая ошибка в консоли:
![image](https://user-images.githubusercontent.com/31287817/226204276-8bace569-3758-45a1-90e9-8e0a6c1a3682.png)

Я так понимаю в коде не случайно остался закоменчиный код для последовательной загрузки песен:
![image](https://user-images.githubusercontent.com/31287817/226204368-b20f7f80-6bc6-409d-aab0-76e65feda82c.png)

Может тогда добавить флаг или параметр для последовательной или параллельной загрузки песен - дать выбор, например...

**Comment by dvjdjvu** [comment]
Без проблем, обновил. **-p** отключить параллельную загрузку.
