### ISSUE TITLE
На последней версии ffmpeg битые песни

### ISSUE THREAD

**Issue by my-dev-92** [dvjdjvu/vkMusicDownloader#8]
Если заиспользовать последнею версию ffmpeg:
![image](https://user-images.githubusercontent.com/31287817/226204532-d564db4f-e597-46d6-af3c-73193470b7e3.png)

то песни после загрузки битые получаются.

**Comment by dvjdjvu** [comment]
Не используйте последнюю версию. От меня тут ни чего не зависит, периодически ffmpeg глючит.

**Comment by my-dev-92** [comment]
> Не используйте последнюю версию. От меня тут ни чего не зависит, периодически ffmpeg глючит.

Ок. Какую версию ffmpeg посоветуете? Или даже на старой версии может глючить?

**Comment by dvjdjvu** [comment]
Экспериментально подберите (т.к. я использую из под Linux Mint какого-то). У людей и у меня периодически проблема с ffmpeg возникает. Может дело даже не в нем а в ВК. Со 2-ого, 3-ого прохода у меня по крайней мере скачивалось без битых файлов.
