### ISSUE TITLE
Код подтверждения где его взять?

### ISSUE THREAD

**Issue by MrKsiJ** [dvjdjvu/vkMusicDownloader#9]
Просит код подтверждения на страницу в лс не приходит SMS не приходит Auth 2FA не подходит

**Comment by dvjdjvu** [comment]
Не понял, что за код подтверждения. Что делаете по шагам и с логами.

**Comment by MrKsiJ** [comment]
> Не понял, что за код подтверждения. Что делаете по шагам и с логами.

У вас в скрипте после ввода пароля просит код подтверждения, однако он не приходит ни по смс не подходит из Authentificator 2FA и вообще не понятно откуда его брать

**Comment by MrKsiJ** [comment]
> Не понял, что за код подтверждения. Что делаете по шагам и с логами.

![image](https://github.com/dvjdjvu/vkMusicDownloader/assets/57679050/08c6a6e3-1b76-4949-badb-ddf29112bbe4)
Вот этот метод в вашем скрипте он срабатывает после ввода пароля

**Comment by dvjdjvu** [comment]
У меня так же не работает теперь. Видимо vk изменил алгоритм авторизации, посмотрю на выходных.

**Comment by dvjdjvu** [comment]
@MrKsiJ проверяйте.

**Comment by MrKsiJ** [comment]
Работает спасибо большое!
